image: "python:3.6"

before_script:
  - apt update
  - python --version
  # pip install -r requirements.txt doesn't work
  # need to install packages by hand
  - apt -y install python-numpy
                   python-scipy
                   python-matplotlib
                   python-lxml
                   python-sqlalchemy
                   python-suds
  - pip install obspy
  - pip install pytest
  - pip install beautifulsoup4
  - pip install pandas

stages:
  - test_weather
  - test_collect_data
  - test_process_data
  - test_plots

# py.test doesn't work, because collect_data not in python path

test:
  stage: test_weather
  script: python -m pytest tests/test_weather_parsing.py

  stage: test_collect_data
  script: python -m pytest tests/test_cd.py

  stage: test_process_data
  script: python -m pytest tests/test_pd.py

  stage: test_plots
  script: python -m pytest tests/test_plots.py