image: "python:3.6"

before_script:
  - apt update
  - python --version
  # pip install -r requirements.txt doesn't work
  # need to install packages by hand
  - apt -y install python-numpy
                   python-scipy
                   python-matplotlib
                   python-lxml
                   python-sqlalchemy
                   python-suds
  - pip install obspy
  - pip install pytest
  - pip install beautifulsoup4

stages:
  - test

test:
  stage: test
  # py.test doesn't work, because collect_data not in python path
  script: python -m pytest tests/

