image: "python:3.6"

before_script:
  - apt update
  - python --version
  - apt -y install python3-pip
  - pip3 install -r requirements.txt

stages:
  - test

test:
  stage: test
  script: python py.test

