test:
  script:
  # install conda env
  - apt-get update -qy
  - apt-get install -y python3-dev
  - python -V
  - apt-get install -y python-pip
  - pip install -r requirements.txt
  # run tests
  - python -V